---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for Dynamic S3 Bucket with Versioning, Encryption, and Public Access Block

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub "dynamic-s3-bucket-${AWS::Region}-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

Outputs:
  S3BucketName:
    Description: "Name of the S3 Bucket"
    Value: !Ref MyS3Bucket
